apiVersion: v1
kind: Service
metadata:
  name: {{ include "tubee-mongodb-metrics.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/path: "/metrics"
  labels:
    app.kubernetes.io/name: {{ include "tubee-mongodb-metrics.name" . }}
    helm.sh/chart: {{ include "tubee-mongodb-metrics.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: exporter
      protocol: TCP
      name: exporter
  selector:
    app.kubernetes.io/name: {{ include "tubee-mongodb-metrics.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
