apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tubee-mongodb-metrics-config
  labels:
    app.kubernetes.io/name: {{ include "tubee-mongodb-metrics.name" . }}
    helm.sh/chart: {{ include "tubee-mongodb-metrics.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
  config.yaml: |
    version: 2.0
    bind: 0.0.0.0:9412
    metricsPath: /metrics
    log:
      encoding: json
      level: info
      development: false
      disableCaller: false
    global:
      queryTimeout: 10
      maxConnection: 3
      defaultCache: 5
    servers:
    - name: main
      uri: mongodb://localhost:27017
    metrics:
    - name: tubee_processes_total
      type: gauge
      help: 'The total number of processes in the queuy labeled by their status'
      value: total
      cacheTime: 5
      realtime: true
      labels: [type,status]
      database: tubee
      collection: taskscheduler
      pipeline: |
        [
          {"$group": {
            "_id":{"status":"$status","name":"$class"},
            "total":{"$sum":1}
          }},
          {"$project":{
            "_id":0,
            "type":"$_id.name",
            "total":"$total",
            "status": {
              "$switch": {
                  "branches": [
                     { "case": { "$eq": ["$_id.status", 0] }, "then": "waiting" },
                     { "case": { "$eq": ["$_id.status", 1] }, "then": "postponed" },
                     { "case": { "$eq": ["$_id.status", 2] }, "then": "processing" },
                     { "case": { "$eq": ["$_id.status", 3] }, "then": "done" },
                     { "case": { "$eq": ["$_id.status", 4] }, "then": "failed" },
                     { "case": { "$eq": ["$_id.status", 5] }, "then": "canceled" },
                     { "case": { "$eq": ["$_id.status", 6] }, "then": "timeout" }
                  ],
                  "default": { "then": "unknown" }
              }}
          }}
        ]    
    - name: tubee_jobs_total
      type: gauge
      help: 'The total number of jobs in the queue labeled by their process status'
      value: total
      cacheTime: 5
      realtime: true
      labels: [name,namespace]
      database: tubee
      collection: jobs
      pipeline: |
        [{
            "$match": {
                "data.active": true
            }
        }, {
            "$lookup": {
                "from": "taskscheduler",
                "let": {
                    "name": "$name",
                    "namespace": "$namespace"
                },
                "as": "procs",
                "pipeline": [{
                    "$match": {
                        "parent": {
                            "$exists": false
                        },
                        "$expr": {
                            "$and": [{
                                "$eq": ["$data.namespace", "$$namespace"]
                            }, {
                                "$eq": ["$data.job", "$$name"]
                            }]
                        }
                    }
                }, {
                    "$sort": {
                        "created": -1
                    }
                }, {
                    "$match": {
                        "status": {
                            "$lt": 3
                        }
                    }
                }]
            }
        }, {
            "$project": {
                "name": 1,
                "namespace": 1,
                "procs": {
                    "$size": "$procs"
                }
            }
        }, {
            "$group": {
                "_id": {
                    "namespace": "$namespace",
                    "name": "$name"
                },
                "total": {
                    "$sum": "$procs"
                }
            }
        },
        {"$project":{
            "_id":0,
            "namespace":"$_id.namespace",
            "name":"$_id.name",
            "total":"$total"
        }}]
    - name: tubee_processes_queued
      type: gauge
      help: 'The total number of processes in the queue'
      value: total
      labels: [total]
      mode: push
      interval: 10
      constLabels: []
      database: tubee
      collection: taskscheduler
      pipeline: |
        [
          {
            "$match": {
              "status": {"$lt":2}
            }
          },
          {"$count": "total"}
        ]
