apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tubee-mongodb-metrics-config
  labels:
    app.kubernetes.io/name: {{ include "tubee-mongodb-metrics.name" . }}
    helm.sh/chart: {{ include "tubee-mongodb-metrics.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
  config.yaml: |
    metrics:
    - name: tubee_processes_total
      type: gauge
      help: 'The total number of processes in the queuy labeled by their status'
      value: total
      cacheTime: 5
      realtime: true
      labels: [type,status]
      database: tubee
      collection: taskscheduler.jobs
      pipeline: |
        [
          {"$group": {
            "_id":{"status":"$status","name":"$class"},
            "total":{"$sum":1}
          }},
          {"$project":{
            "_id":0,
            "type":"$_id.name",
            "total":"$total",
            "status": {
              "$switch": {
                  "branches": [
                     { "case": { "$eq": ["$_id.status", 0] }, "then": "waiting" },
                     { "case": { "$eq": ["$_id.status", 1] }, "then": "postponed" },
                     { "case": { "$eq": ["$_id.status", 2] }, "then": "processing" },
                     { "case": { "$eq": ["$_id.status", 3] }, "then": "done" },
                     { "case": { "$eq": ["$_id.status", 4] }, "then": "failed" },
                     { "case": { "$eq": ["$_id.status", 5] }, "then": "canceled" },
                     { "case": { "$eq": ["$_id.status", 6] }, "then": "timeout" }
                  ],
                  "default": { "then": "unknown" }
              }}
          }}
        ]    
