apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tubee-jobs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "tubee-jobs.name" . }}
    helm.sh/chart: {{ include "tubee-jobs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tubee-jobs.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tubee-jobs.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - tubeecli
            - jobs
            - -vvvv
          env:
            - name: TUBEE_MONGODB_URI
            {{- if .Values.mongodbURI }}
              value: {{ .Values.mongodbURI }}
            {{- else }}
              value: mongodb://{{ .Release.Name }}-mongodb-0.{{ .Release.Name }}-mongodb:27017,{{ .Release.Name }}-mongodb-1.{{ .Release.Name }}-mongodb:27017,{{ .Release.Name }}-mongodb-2.{{ .Release.Name }}-mongodb:27017
            {{- end }}
{{- if .Values.extraVars }}
{{ toYaml .Values.extraVars | indent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /etc/tubee
              name: config-volume
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
         - configMap:
             defaultMode: 420
             name: {{ .Release.Name }}-tubee-config
           name: config-volume
         {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
