apiVersion: v1
kind: ConfigMap
{{- if .Files.Get "config/config.yaml" }}
data:
  config.yaml: {{ .Files.Get "config/config.yaml" | toYaml | indent 2}}
{{- end }}
metadata:
  name: {{ .Release.Name }}-tubee-config
  labels:
    app.kubernetes.io/name: {{ include "tubee-api.name" . }}
    helm.sh/chart: {{ include "tubee-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
