apiVersion: v1
name: tubee-jobs
description: tubee jobs runner
type: application
version: 1.0.3
appVersion: 1.1.0-alpha.1
keywords:
- tubee
home: https://github.com/gyselroth/tubee
sources:
- https://github.com/gyselroth/tubee-helm
maintainers:
- name: Sandro Aebischer
  email: aebischer@gyselroth.com
