apiVersion: v1
name: tubee-jobs
description: tubee jobs runner
type: application
version: 0.0.2
appVersion: 1.0.0-beta56
keywords:
- tubee
home: https://github.com/gyselroth/tubee
sources:
- https://github.com/gyselroth/tubee-helm
maintainers:
- name: Raffael Sahli
  email: sahli@gyselroth.com
